op-rs/maili

Cargo.toml
README.md
book/src/links.md
book/src/starting.md
crates/provider/Cargo.toml
crates/provider/src/ext/engine.rs
crates/rpc-types-engine/Cargo.toml
crates/rpc-types-engine/README.md
crates/rpc-types-engine/src/lib.rs
crates/rpc-types-engine/src/superchain.rs

Migrates L2 types in `op-alloy-rpc-types-engine` to `maili-rpc-types-engine`.
We may want to put these in another crate, like `maili-types`, nonetheless this is the first step to incrementally updating deps in `op-alloy`.

chore(engine): Migrate types in engine rpc types from `op-alloy`

---

Cargo.toml
crates/maili/Cargo.toml
crates/maili/README.md
crates/maili/src/lib.rs

Adds the `Maili` crate which re-exports all `maili-*` crates in the workspace.

chore: Maili Re-export Crate

---

crates/registry/README.md

Updates `maili-registry` version in README

fix(docs): Update `maili-registry` version in readme

---

Cargo.toml
crates/rpc-jsonrpsee/Cargo.toml
crates/rpc-jsonrpsee/README.md
crates/rpc-jsonrpsee/src/lib.rs
crates/rpc-jsonrpsee/src/traits.rs

Migrates `alloy-rs/op-alloy-rpc-jsonrpsee` to `op-rs/maili-rpc-jsonrpsee`.

chore(rpc): Migrate `alloy-rs/op-alloy-rpc-jsonrpsee`->`op-rs/maili-rpc-jsonrpsee`

---

Cargo.toml
crates/protocol/Cargo.toml
crates/protocol/src/channel_out.rs

Fixes `ChannelOut` to correctly randomize the `ChannelId` on reset using the [operating system's randomness](https://docs.rs/rand/latest/rand/rngs/struct.OsRng.html).

fix(protocol): Channel ID Randomization

---

Cargo.toml

chore(deps): bump op-alloy to 0.9.2

---

crates/rpc-jsonrpsee/src/traits.rs

Passes a slice of `EngineMessages` instead of a vector in `SupervisorApi::check_messages`

perf(rpc): Smol perf improvement `SupervisorApi`, pass slice instead of vec as param

---

Cargo.toml
README.md
book/src/links.md
book/src/starting.md
crates/common/Cargo.toml
crates/common/README.md
crates/common/src/deposit_source.rs
crates/common/src/lib.rs
crates/common/src/superchain.rs
crates/maili/Cargo.toml
crates/maili/src/lib.rs
crates/provider/Cargo.toml
crates/provider/src/ext/engine.rs
crates/rpc-jsonrpsee/Cargo.toml
crates/rpc-jsonrpsee/src/traits.rs

Migrates `op_alloy_consensus::transaction::source` to `maili_common::deposit_source`.

chore(common): Migrate deposit source types from `op-alloy`

---

Cargo.toml
crates/common/README.md
crates/maili/Cargo.toml
crates/maili/README.md
crates/maili/src/lib.rs

Fixes up the `maili` crate to include `maili-rpc-jsonrpsee` and some feature fixes.

fix(maili): Missing Crates

---

scripts/check_no_std.sh

Add `no_std` maili crates to `no_std` check script.

fix: Add Crates to no_std Checks

---

crates/protocol/Cargo.toml

Re-enables `maili-protocol/serde` in dev-deps

fix(no-std): Fix broken test in `no_std` `maili-protocol`

---

crates/provider/Cargo.toml
crates/provider/src/ext/engine.rs

Ideally, alloy would divide the `EngineApi` trait into `EngineApiV1`, `EngineApiV2`, etc. However since this is not the case atm, `OpEngineApi` can't have `EngineApi` as super trait since it doesn't support V1. Nonetheless, these methods aren't unique to l2, and hence better move back to op-alloy, leaving only OP unique method `engine_signalSuperchainV1` in maili for now. `op_alloy_provider::OpEngineApi` should have `maili_provider::EngineExtApi` as supertrait.
We may want to rename this crate or move the trait into protocol?

chore(provider): Shrink scope of `OpEngineApi` to encompass only non-l1 methods

---

.github/workflows/sync.yml

Adds a workflow that is run on a cron job daily, and can be manually dispatched.
The Submodule Sync workflow updates the [`superchain-registry`](https://github.com/ethereum-optimism/superchain-registry/tree/main) git submodule and opens a PR into `main` with the updated ref.
This keeps `maili-registry`'s bindings up to date with the upstream `superchain-registry`

chore: Submodule Sync

---

.github/ISSUE_TEMPLATE/BUG-FORM.yml
.github/ISSUE_TEMPLATE/FEATURE-FORM.yml
.github/ISSUE_TEMPLATE/config.yml

Closes #23
Adds default `D-needs-triage` label to issues.
Also adds respective `C-feat` and `C-bug` labels.
Disables blank issues so these labels must be applied to new issues.

chore: Issue Tracking

---

Cargo.toml
crates/common/Cargo.toml
crates/common/src/deposit/envelope.rs
crates/common/src/deposit/mod.rs
crates/common/src/lib.rs
crates/protocol/Cargo.toml
crates/protocol/examples/batch_to_frames.rs
crates/protocol/examples/frames_to_batch.rs
crates/protocol/src/batch/single.rs
crates/protocol/src/batch/span.rs
crates/protocol/src/deposits.rs
crates/protocol/src/info/variant.rs

Migrates `TxDeposit` from `op-alloy`. Removes dependency on `op-alloy` in lib.

Migrate `TxDeposit` from `op-alloy`

---

book/src/links.md

Adds `maili-rpc` and `maili-genesis` to book links

chore(docs): Add missing links in book

---

README.md
book/src/links.md
crates/genesis/README.md
crates/maili/README.md

Fixes broken readme links and updates links pointing to `anton-rs` to point to `op-rs`

fix(docs): Fix readme links

---

crates/protocol/src/info/interop.rs
crates/protocol/src/info/mod.rs
crates/protocol/src/info/variant.rs
crates/protocol/src/lib.rs
crates/protocol/src/utils.rs

Adds the new `L1BlockInfo` transaction variant for the Interop hardfork, as not specified (😠) but implemented in the `op-node`: https://github.com/ethereum-optimism/optimism/blob/a51637c0bb42a2a5f579d0b0ac7a8975f4d47dc5/op-node/rollup/derive/l1_block_info.go#L4

feat(protocol): `L1BlockInfoInterop`

---

crates/protocol/src/deposits.rs
crates/protocol/src/info/deposit_context.rs
crates/protocol/src/info/mod.rs
crates/protocol/src/info/variant.rs
crates/protocol/src/lib.rs

Adds a function for creating the new closing transaction for the deposit context, after the interop hardfork activates. This will be used by `kona-derive`'s attributes builder and placed as the final deposit transaction in payloads at + after interop activation.
spec: https://specs.optimism.io/interop/derivation.html#closing-the-deposit-context

feat(protocol): Deposit context closing tx formation

---

crates/flz/Cargo.toml
crates/flz/src/lib.rs

Re-exports compression and decompression from `fastlz` crate optionally.

chore(flz): Compression Re-exports

---

book/src/building/protocol/batches.md
crates/protocol/src/batch/span.rs

Add more unit test for `SpanBatch`, namely:
- Batch block timestamp less than L1 origin
- Overlapping block tx count mismatch
- Overlapping block tx content match
- Missing L1 origin for singular batch
Closes #20

Add more Span Batch unit tests

---

CHANGELOG.md

The `0.1.6` release forgot this crate.

fix: release maili 0.1.6

---

CHANGELOG.md

Missing `maili-serde` crate release.

fix: maili-serde release

---

CHANGELOG.md

Release missing `maili-superchain` crate.

fix(release): maili-superchain

---

crates/protocol/src/fee.rs

The tx size estimation must be a `u64` value by the formula.
Explicitly use `u64` so downstream users don't need to unwrap the `U256` into a `u64` type.
See: https://github.com/paradigmxyz/reth/pull/13905#discussion_r1924141257

fix(protocol): Fix u64 return for tx size estimation

---

Cargo.toml
dist-workspace.toml

Experimenting with `dist` to automagically publish releases with tags.

test: cargo-dist

---

.config/zepter.yaml
.github/workflows/lint.yml
crates/genesis/Cargo.toml
crates/interop/Cargo.toml
crates/maili/Cargo.toml
crates/protocol/Cargo.toml
crates/registry/Cargo.toml
crates/registry/superchain/Cargo.toml
crates/rpc/Cargo.toml
crates/serde/Cargo.toml
deny.toml

Closes #21. Adds feature propagation checks, in a new file to avoid clogging up the existing jobs.
Lmk if we'd like to move this somewhere else!

feat(ci): feature propagation checks

---

crates/protocol/src/batch/mod.rs
crates/protocol/src/batch/transactions.rs
crates/protocol/src/batch/tx_data/eip1559.rs
crates/protocol/src/batch/tx_data/eip7702.rs
crates/protocol/src/batch/tx_data/mod.rs
crates/protocol/src/batch/tx_data/wrapper.rs
crates/protocol/src/lib.rs

Adds support for serializing and deserializing EIP-7702 transactions in a span batch which will be required to implement EIP-7702 in Isthmus. Fixes #84

feat: implement EIP-7702 span batch support

---

crates/rpc/Cargo.toml
crates/rpc/src/api.rs
crates/rpc/src/lib.rs
crates/rpc/src/supervisor.rs
crates/rpc/src/traits.rs

Add ExecutingMessageValidator trait

---

Cargo.toml
crates/rpc/Cargo.toml

Without revm's default features off, the `blst` and `std` features are enabled, breaking it's use in `maili-genesis` within a `no_std` context.

fix: Turn revm defaults off

---

crates/interop/src/lib.rs
crates/interop/src/message.rs
crates/interop/src/root.rs

Tighten `no_std` restrictions for tests.
General cleanup of `maili-interop`.

chore: clean up maili-interop

---

Justfile
crates/registry/Justfile
crates/registry/build.rs

Updates the `maili-registry` build to print a pretty warning if the scr is missing.
Fixes #152

chore(registry): Pretty Missing Submodule Warnings

---

crates/registry/build.rs
crates/registry/etc/configs.json

Previously, we had a bunch of `[BOT] Update Submodules` prs that just re-ordered chains and superchains in the output `configs.json` artifact.
This PR fixes this by sorting superchains by name and chains by their l2 chain id. This should reduce the frequency of `[BOT] Update Submodules` prs since there won't be a sorting diff.

chore(registry): Sort Superchains and Chains

---

crates/genesis/src/genesis.rs
crates/genesis/src/lib.rs
crates/genesis/src/rollup.rs
crates/genesis/src/system.rs
crates/protocol/src/info/errors.rs
crates/protocol/src/info/isthmus.rs
crates/protocol/src/info/mod.rs
crates/protocol/src/info/variant.rs
crates/protocol/src/lib.rs
crates/protocol/src/utils.rs
crates/registry/etc/configs.json
crates/registry/src/test_utils/base_mainnet.rs
crates/registry/src/test_utils/base_sepolia.rs
crates/registry/src/test_utils/op_mainnet.rs
crates/registry/src/test_utils/op_sepolia.rs

Defines `L1BlockInfoIsthmus` in maili-protocol to include the new operator fee scalar and operator fee constant.
Original PR in `op-alloy`: https://github.com/alloy-rs/op-alloy/pull/130
[Design Doc](https://github.com/ethereum-optimism/design-docs/pull/81)
[Spec](https://github.com/ethereum-optimism/specs/pull/382/files).

feat(protocol): Operator Fee

---

crates/rpc/src/attributes.rs
crates/rpc/src/net.rs
crates/rpc/src/superchain.rs

Adds test coverage to the `maili-rpc` crate.

chore(rpc): Test Coverage

---

crates/protocol/src/batch/span.rs

Fixes the span batch validation logic to invalidate a **pre-Holocene** span batch entirely if a single batch
within the span batch contains an EIP-7702 transaction.

fix(protocol): Pre-Holocene SB Invalidation for EIP-7702

---

crates/registry/build.rs

Returns early in the custom `maili-registry` build script when a filesystem is read-only.
This _should_ fix the docs.rs build issues.

fix(registry): Return Build Script on Read-Only FS

---

crates/registry/Justfile
crates/registry/build.rs

Fixes the `maili-registry` build script to _only_ bind when the `MAILI_BIND` environment variable is set to "true".
Otherwise return early from the script.

fix(registry): Only bind with MAILI_BIND

---

crates/protocol/src/info/variant.rs

L1 block info variant testing.

chore(protocol): L1 Block Info Variant Testing

---

.github/codecov.yml
crates/genesis/src/chain/addresses.rs
crates/genesis/src/chain/altda.rs
crates/genesis/src/chain/config.rs
crates/genesis/src/chain/hardfork.rs
crates/genesis/src/chain/roles.rs
crates/genesis/src/genesis.rs
crates/genesis/src/lib.rs
crates/genesis/src/params.rs
crates/genesis/src/rollup.rs
crates/genesis/src/superchain/level.rs
crates/genesis/src/system/config.rs
crates/genesis/src/updates/batcher.rs
crates/genesis/src/updates/eip1559.rs
crates/genesis/src/updates/gas_config.rs
crates/genesis/src/updates/gas_limit.rs
crates/genesis/src/updates/operator_fee.rs

Removes `std` restriction for `maili-genesis` tests.

chore(genesis): Remove std restriction for genesis tests

---

crates/protocol/src/deposits.rs

Fixes deposit tests.
Closes #232
Closes #233

chore(protocol): Deposit Tests

---

crates/protocol/src/info/bedrock.rs
crates/protocol/src/info/ecotone.rs
crates/protocol/src/info/errors.rs
crates/protocol/src/info/interop.rs
crates/protocol/src/info/isthmus.rs
crates/protocol/src/info/variant.rs

Re-jiggers the `L1BlockInfoTx` calldata parsing to use concrete error types and direct slice referencing with safety.
This avoids missing test coverage over errors that cannot be thrown due to bound checks.
Closes #229

chore(protocol): Rejigger L1 Block Info Tx Calldata Parsing

---

crates/protocol/src/batch/span.rs

Fixes the `maili-protocol` overlapped transaction test.
Closes #220

chore(protocol): Overlapped Tx

---

crates/rpc/Cargo.toml
crates/rpc/src/lib.rs

Fixes the unused dependency warning for `alloy_sol_types` by making the `interop` feature flag depend on `jsonrpsee` and `client`, which it effectively already does since interop traits cannot be used without all three features being enabled.
Closes #230

chore(rpc): Interop Feat Flag Cleanup - Unused Dependency Warning Fix
