- Cargo.toml
- book/src/links.md
- crates/registry/README.md
Fixes bugs introduced by https://github.com/op-rs/maili/pull/2
> fix(registry): reset version of registry in workspace manifest and fix book links

- CHANGELOG.md
`0.1.0` release of `maili-*` crates
> release: 0.1.0

- README.md
Touches up the readme to use crate shields with their versions for concisiveness.
> chore: Crate Shields

- README.md
Smol PR to fix the readme badges
> chore: Fix README Shields

- .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
Updates issues template to include provider component
> chore(meta): Update issue template to include provider

- crates/registry/src/lib.rs
- crates/rpc-types-engine/src/lib.rs
Update doc headers of `maili-registry` and `maili-rpc-types-engine`
> chore(docs): Update doc headers

- RELEASES.md
Adds a super-concise release document for posterity.
> chore: Document Crate Releases

- CHANGELOG.md
- Cargo.toml
> release: 0.1.2

- CHANGELOG.md
- Cargo.toml
- crates/protocol/Cargo.toml
> fix: maili-protocol cyclical dep

- CHANGELOG.md
> release: 0.1.3

- README.md
Micro PR to add the `maili-rpc` badge to the readme.
> chore: Readme Badge

- CHANGELOG.md
- Cargo.toml
> release: 0.1.4

- README.md
- book/src/starting.md
Updates book and workspace readme to include `maili-rpc`
> chore(docs): Update docs to include rpc

- Cargo.toml
- crates/protocol/Cargo.toml
- crates/protocol/src/batch/span.rs
> chore(deps): Bump `op-alloy` to 0.9.3

- CHANGELOG.md
One-off release for `maili-genesis`.
> release: maili-genesis

- CHANGELOG.md
- Cargo.toml
Second batch of crates released as part of `0.1.5`
> release: 0.1.5 part 2

- CHANGELOG.md
- Cargo.toml
> release: 0.1.5

- crates/registry/etc/chainList.json
- crates/registry/etc/configs.json
Automated PR to update git submodules.
> [BOT] Update Submodules

- crates/protocol/src/info/variant.rs
Flattens the `L1BlockInfoTx::try_new` method internals to make it cleaner and more easily digestible/extensible.
> chore(protocol): Flatten L1BlockInfoTx::try_new Method

- CHANGELOG.md
- Cargo.toml
> feat(workspace): Release 0.1.6

- crates/flz/src/lib.rs
Touches up the `maili-flz` docs.
> chore(flz): Touchup FLZ docs

- CHANGELOG.md
- Cargo.toml
Releases `0.1.7` maili crates.
> release: 0.1.7

- Cargo.toml
- crates/interop/Cargo.toml
- crates/interop/README.md
- crates/interop/src/constants.rs
- crates/interop/src/lib.rs
- crates/interop/src/message.rs
- crates/interop/src/safety.rs
Introduces the most minimal set of interop types required to define the supervisor api for `op-reth`.
> feat: interop crate

- CHANGELOG.md
- Cargo.toml
Releases `maili-*` crates `0.1.9`.
> release: 0.1.9

- CHANGELOG.md
- Cargo.toml
> release: 0.1.10

- CHANGELOG.md
- Cargo.toml
> release: 0.1.11

- CHANGELOG.md
- Cargo.toml
Contains `0.2.0` release artifacts
> release: 0.2.0

- crates/registry/build.rs
- crates/registry/etc/configs.json
Pretty print the superchain-registry configs file.
Motivation: This makes the line diff easier to digest for scr updates since.
> chore(registry): Pretty Print SCR Configs

- Cargo.toml
Micro PR to update the `op-alloy` deps to `0.10.1`
> chore: Alloy Dep Bump

- crates/genesis/src/system.rs
Small fix for the operator fee parsing.
> fix(genesis): Small Operator Fee Fix

- README.md
> chore: Touchup README

- CHANGELOG.md
- Cargo.toml
Adds release artifacts `0.2.1`
> release: 0.2.1

- README.md
- book/src/starting.md
- scripts/check_no_std.sh
> chore: Touchups and no_std checks

- crates/registry/etc/configs.json
- crates/registry/superchain/src/lib.rs
Fixes the bad serialization of types in `maili-superchain`.
> fix(superchain): Bad Superchain Types

- crates/genesis/src/chain/addresses.rs
- crates/genesis/src/chain/altda.rs
- crates/genesis/src/chain/hardfork.rs
- crates/genesis/src/chain/roles.rs
- crates/genesis/src/chain/superchain.rs
- crates/registry/etc/configs.json
- crates/registry/src/superchain.rs
Update the genesis types in `maili-genesis` to be inline with the superchain-registry.
> chore(genesis): Cleanup Types

- crates/registry/superchain/README.md
> chore: Deprecate Maili-superchain

- .github/codecov.yml
- .github/workflows/coverage.yml
Adds the [codecov](https://github.com/op-rs/kona/blob/main/.github/workflows/rust_ci.yaml) workflow from [kona](https://github.com/op-rs/kona).
> feat: Code Coverage

- crates/protocol/src/channel.rs
Increases test coverage over the channel.
> chore(protocol): Channel Test Coverage

- .github/codecov.yml
- crates/protocol/src/channel_out.rs
- crates/protocol/src/test_utils.rs
fixes up code coverage for `ChannelOut`
> chore(protocol): ChannelOut Coverage

- crates/genesis/src/params.rs
Adds test coverage across base fee params methods.
> chore(genesis): Base Fee Params Testing

- crates/genesis/src/updates/batcher.rs
- crates/genesis/src/updates/eip1559.rs
Adds test coverage to the batcher update.
> chore(genesis): Batcher Update Test Coverage

- crates/protocol/src/compression/ratio.rs
> chore(protocol): Increase Test Coverage

- crates/genesis/src/updates/operator_fee.rs
Adds tests for the operator fee update sad paths.
> chore(genesis): Operator Fee Update Tests

- crates/protocol/src/channel_out.rs
- crates/protocol/src/test_utils.rs
Adds test coverage for outputting a frame.
> chore(protocol): Test Coverage for Outputting a Frame

- CHANGELOG.md
- Cargo.toml
Release artifacts for `maili` v `0.2.3`.
> release: 0.2.3

- crates/protocol/src/batch/single.rs
- crates/protocol/src/lib.rs
- crates/protocol/src/utils.rs
- crates/registry/etc/chainList.json
- crates/registry/etc/configs.json
Updates `maili-protocol` to drop a single batch if it contains any EIP-7702 transactions pre-isthmus hardfork.
Closes https://github.com/op-rs/kona/issues/1015
> feat(protocol): Pre-isthmus, Invalidate Single Batches with EIP-7702 txs

- crates/protocol/src/batch/single.rs
Adds more validation tests for single batches.
> chore(protocol): Single Batch Validation Tests

- Cargo.toml
Bumps `op-alloy` deps to `0.10.3`
> chore: Bump op-alloy deps

- CHANGELOG.md
- Cargo.toml
> release: 0.2.4

- CHANGELOG.md
- Cargo.toml
> release: 0.2.5

- Cargo.toml
> release: 0.2.6

- crates/protocol/src/block.rs
- crates/protocol/src/info/errors.rs
Increases test coverage over block.
> chore(protocol): Block Test Coverage

- crates/protocol/src/info/deposit_context.rs
Deposit context test coverage.
> chore(protocol): Deposit Context Test Coverage

- crates/protocol/src/info/variant.rs
Adds more l1 block info variant testing.
> chore(protocol): Variant Testing

- crates/registry/src/lib.rs
- crates/registry/src/superchain.rs
- crates/registry/superchain/README.md
Removes feature leakage in `maili-registry` tests
> chore(registry): Remove std feature leakage in tests

- Cargo.toml
> release: 0.2.8

- deny.toml
> chore: Cleanup deny.toml

- crates/protocol/src/info/variant.rs
Fix variant test coverage including isthmus.
> chore(protocol): Variant Test Coverage

- crates/protocol/src/batch/tx_data/eip7702.rs
Adds test coverage over the EIP-7702 span batch tx data.
Closes #228
> chore(protocol): Test Coverage over EIP-7702

- crates/protocol/src/batch/span.rs
Adds test coverage over span batch.
#227
> chore(protocol): Test Coverage over Span Batch

- crates/interop/Cargo.toml
- crates/interop/src/lib.rs
- crates/interop/src/supervisor.rs
- crates/rpc/Cargo.toml
- crates/rpc/src/lib.rs
- crates/rpc/src/traits.rs
Fixes the supervisor client api.
Closes #238.
> chore(rpc): Supervisor Api Fixes
